export const musicLinks = {
  charm: "/Songs/Charm - Rema.m4a",
  calmDown: "/Songs/Calm Down - Rema&Selena.m4a",
  holiday: "/Songs/Holiday - Rema.m4a",
  basquiat: "/Songs/Basquiat - Asake.m4a",
  lonelyAtTheTop: "/Songs/Lonely At The Top - Asake.m4a",
  twoThirty: "/Songs/Asake - 2.30.m4a",
  remember: "/Songs/Asake - Remember.mp3",
  sunshine: "/Songs/Asake - Sunshine.mp3",
  modupe: "/Songs/Modupe - Crayon.m4a",
  Ngozi: "/Songs/Ngozi - Crayon&Ayra Starr.m4a",
  belleFull: "/Songs/Crayon - Belle Full feat Victony & Ktizo.m4a",
  ijoLaba: "/Songs/Crayon - Ijo (Laba Laba).mp3",
  reason: "/Songs/reason - Omah Lay.m4a",
  comeCloser: "/Songs/Omah Lay - Come Closer.mp3",
  itsYours: "/Songs/Omah Lay - Its Yours.mp3",
  soso: "/Songs/Omah Lay - Soso ft Ozuna.m4a",
  manOfTheYear: "/Songs/Seyi Vibez - Man of The Year.mp3",
  dejavu: "/Songs/Seyi Vibez - Dejavu.mp3",
  karma: "/Songs/Seyi Vibez - Karma.mp3",
  unavailable: "/Songs/UNAVAILABLE(feat. Musa Keys) - Davido.m4a",
  feel: "/Songs/Davido - Feel.mp3",
  noCompetition: "/Songs/Davido ft Asake - No Competition.mp3",
  inTheGarden: "/Songs/Davido - IN THE GARDEN feat Morravey.mp3",
  chemical: "/Songs/Chemical - Post Malone.m4a",
  betterNow: "/Songs/Post Malone - Better Now.mp3",
  circles: "/Songs/Post malone - Circles.mp3",
  sunflower: "/Songs/Post Malone, Swae Lee - Sunflower.mp3",
};
